server:
  port: 18083

spring:
  application:
    name: cloud-payment-service

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3307/payment?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456

#注册到eureka
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
#      defaultZone: http://localhost:17071/eureka  #单机版
      defaultZone: http://eureka17071.com:17071/eureka,http://eureka17072.com:17072/eureka  #集群版
  instance:
    instance-id: payment18083
    prefer-ip-address: true # 访问路径可以显示IP信息

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.andrew.springcloud.entities
