server:
  port: 17072

eureka:
  instance:
    hostname: eureka17072.com #eureka服务端的实例名称
  client:
    register-with-eureka: false
    #false 表示自己就是注册中心，不需要检索服务
    fetch-registry: false
    service-url:
      #设置与Eureka server 交互的地址查询服务和注册服务都需要依赖这个地址
      defaultZone: http://eureka17071.com:17071/eureka/