server:
  port: 17075
eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      defaultZone: http://eureka17071.com:17071/eureka
#      defaultZone: http://eureka17071.com:17071/eureka,http://eureka17072.com:17072/eureka
feign:
  hystrix:
    enabled: true

