server:
  # consul服务端口
  port: 18086
spring:
  application:
    name: consul-provider-payment
  cloud:
    consul:
      # consul注册中心地址
      host: 192.168.100.100
      port: 8500
      discovery:
        hostname: 127.0.0.1
        service-name: ${spring.application.name}
        prefer-ip-address: true
