server:
  port: 18087
spring:
  application:
    name: cloud-provider-hystrix-payment
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka17071.com:17071/eureka
#      defaultZone: http://eureka17071.com:17071/eureka,http://eureka17072.com:17072/eureka


