server:
  port: 18082

spring:
  application:
    name: cloud-consumer-order

#注册到eureka
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
#      defaultZone: http://localhost:17071/eureka  #单机版
      defaultZone: http://eureka17071.com:17071/eureka,http://eureka17072.com:17072/eureka  #集群版